# This is the configuration file for Cardboard

# Invoke ChatEvent from PlayerManager instead of NetworkHandler
# This can solve issues with other mods that overwrite the chat method,
use_alternative_chat_mixin: false

# Registry Command Fix
# Commands like "/give" or "/setblock" don't work when
# executed by entities unless "minecraft:" prefix is specified.
# Enabling will break chat signatures.
registry-command-fix: true

# Reflection Remapper Skip
# Our current Reflection remapper might cause issues with some plugins
# You can add plugin names here (that dont use Reflection) to our SKIP array
skip_reflection_for_plugin:
	- vault
	- worldguard

# Forcefully Disable Mixins - If a mixin is causing an issue you can disable it here
mixin-force-disable:
	- None