name: Minecraft Server

on:
  workflow_dispatch:  # manual start
  push:               # optional: auto-run on push
    branches: [ main ]

jobs:
  run-server:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Minecraft Server with Playit
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x playit-windows-x86_64-signed.exe

          echo "Starting Playit tunnel..."
          ./playit-windows-x86_64-signed.exe &
          PLAYIT_PID=$!
          echo "Playit started with PID $PLAYIT_PID"

          echo "Starting Spigot..."
          # Start spigot with stdin kept open (so we can send /stop later)
          java -Xms16G -Xmx16G -jar launcher.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          SPIGOT_PID=$!
          echo "Spigot started with PID $SPIGOT_PID"

          # Function to send commands to Spigot console
          send_spigot_cmd() {
            echo "$1" > /proc/$SPIGOT_PID/fd/0
          }

          # Timer: 5h55m (21300 sec)
          (
            sleep 60
            echo "⏰ 5h55m reached → shutting down..."

            # Kill playit first (cut external access)
            kill -9 $PLAYIT_PID || true
            echo "Playit stopped."

            # Send /stop to Spigot console
            echo "Sending /stop to Spigot..."
            send_spigot_cmd "stop"

            # Failsafe: if not stopped after 2 min, force kill
            sleep 120
            if kill -0 $SPIGOT_PID 2>/dev/null; then
              echo "⚠️ Spigot did not stop → force killing..."
              kill -9 $SPIGOT_PID || true
            fi
          ) &

          # Wait until spigot exits
          wait $SPIGOT_PID

      - name: Commit world save
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-save world at $(date)" || echo "No changes to commit"
          git push
