name: Minecraft Server Auto Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-22.04
    timeout-minutes: 360 # GitHub max runtime 6h

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}

      - name: Setup Java (GraalVM 22)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Server + Playit
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x playit-linux-amd64
          echo "$PLAYIT_SECRET" > playit.toml

          echo "Starting Spigot..."
          java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Xms16G -Xmx16G -jar server.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          SPIGOT_PID=$!
          echo "Spigot started with PID $SPIGOT_PID"

          echo "Starting playit..."
          ./playit-linux-amd64 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          PLAYIT_PID=$!
          echo "Playit started with PID $PLAYIT_PID"

          echo $SPIGOT_PID > spigot.pid
          echo $PLAYIT_PID > playit.pid

      - name: Auto Commit Loop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          cancel_old_workflow_runs() {
            RUNS=$(gh api repos/$REPO/actions/runs --paginate \
              -q '.workflow_runs[] | select(.status=="in_progress" and .id != '${GITHUB_RUN_ID}') | .id')
            for RUN_ID in $RUNS; do
              echo "Cancelling workflow run $RUN_ID"
              gh api repos/$REPO/actions/runs/$RUN_ID/cancel -X POST
            done
          }

          commit_and_push() {
            date > heartbeat.txt
            git add heartbeat.txt
            git commit -m "Heartbeat at $(date)" || true
            git push origin main || return 1
          }

          cancel_old_workflow_runs

          end=$((SECONDS+21540)) # 5h59m
          while [ $SECONDS -lt $end ]; do
            if ! commit_and_push; then
              echo "Commit failed, retrying..."
            fi
            cancel_old_workflow_runs
            sleep 5
          done

          echo "Stopping Spigot and Playit gracefully..."
          kill -TERM $(cat spigot.pid) || true
          kill -TERM $(cat playit.pid) || true
          sleep 20 # give processes time to shut down

          echo "Restarting workflow..."
          echo "Restart triggered at $(date)" > restart.txt
          git add restart.txt
          git commit -m "Restart workflow at $(date)" || true
          git push origin main
