name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - List directory contents
        run: ls -la

      - name: Run Spigot and playit with 5-second commits and workflow cleanup
        if: "!contains(github.event.head_commit.message, 'Auto commit every 5 seconds')"
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }}
          PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x playit-linux-amd64
          echo "$PLAYIT_SECRET" > playit.toml
          echo "Downloading Spigot.."
          echo "Starting Spigot..."
          java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Xms16G -Xmx16G -jar server.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          SPIGOT_PID=$!
          echo "Spigot started with PID $SPIGOT_PID"
          echo "Starting playit..."
          ./playit-linux-amd64 >/dev/null 2>&1 &
          PLAYIT_PID=$!
          echo "playit started with PID $PLAYIT_PID"

          # -------- Functions (same style) --------
          commit_and_push() {
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git reset -- playit.toml
            git reset -- playit.log
            git reset -- tunnel-config.yml
            git reset -- credentials.json
            git reset -- logs/
            if ! git commit -m "Auto commit every 5 seconds [no ci]"; then
              echo "No changes to commit or commit failed"
              return 1
            fi
            for i in {1..3}; do
              if git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:main --force; then
                echo "Push successful on attempt $i"
                return 0
              else
                echo "Push failed on attempt $i, retrying..."
                git pull --rebase
              fi
            done
            echo "Failed to push after 3 attempts"
            return 1
          }

          start_spigot() {
            echo "Starting Spigot..."
            java -Xms16G -Xmx16G -jar launcher.jar nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
            SPIGOT_PID=$!
            echo "Spigot started with PID $SPIGOT_PID"
          }

          delete_auto_commit_workflows() {
            workflow_ids=$(curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
              "https://api.github.com/repos/${REPO}/actions/runs" | \
              jq '.workflow_runs[] | select(.head_commit.message | contains("Auto commit every 5 seconds [no ci]")) | .id')
            for id in $workflow_ids; do
              echo "Deleting workflow run $id"
              curl -s -X DELETE -H "Authorization: token $FINE_GRAINED_PAT" \
                "https://api.github.com/repos/${REPO}/actions/runs/$id"
            done
          }

          create_new_workflow_run() {
            curl -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${REPO}/actions/workflows/blank.yml/dispatches" \
              -d '{"ref":"main"}'
            echo "New workflow run created"
          }

          cancel_old_workflow_runs() {
            current_run_id=$GITHUB_RUN_ID
            # paginate to ensure all older runs are canceled
            page=1
            while : ; do
              workflow_runs=$(curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
                "https://api.github.com/repos/${REPO}/actions/runs?branch=main&status=in_progress&per_page=100&page=$page")
              run_ids=$(echo "$workflow_runs" | jq -r ".workflow_runs[] | select(.id != $current_run_id) | .id")
              [ -z "$run_ids" ] && break
              for run_id in $run_ids; do
                echo "Cancelling workflow run $run_id"
                curl -s -X POST -H "Authorization: token $FINE_GRAINED_PAT" \
                  "https://api.github.com/repos/${REPO}/actions/runs/$run_id/cancel"
              done
              page=$((page+1))
            done
          }

          START_TIME=$(date +%s)
          # optional background cleanup (kept to match your style)
          (sleep 30 && cancel_old_workflow_runs) &
          (sleep 20 && rm -f credentials.json) &

          while true; do
            if ! commit_and_push; then
              echo "Commit and push failed, continuing without stopping the workflow"
            fi

            cancel_old_workflow_runs

            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

            if ! kill -0 $SPIGOT_PID 2>/dev/null; then
              echo "Spigot process has stopped. Restarting Spigot..."
              start_spigot
            fi

            # Graceful stop at 5h59m OR if Playit died
            if ! kill -0 $PLAYIT_PID 2>/dev/null || [ $ELAPSED_TIME -ge 21540 ]; then
              if ! kill -0 $PLAYIT_PID 2>/dev/null; then
                echo "PlayIt Tunnel process has stopped."
              else
                echo "Workflow has been running for ~5h59m. Stopping processes gracefully..."
              fi
              # graceful shutdown
              kill -TERM $SPIGOT_PID || true
              kill -TERM $PLAYIT_PID || true
              sleep 20

              echo "Creating new workflow run and exiting current one."
              create_new_workflow_run
              exit 0
            fi

            # commit every 5 seconds
            sleep 5
          done

      - name: Rerun workflow if previous step failed
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/blank.yml/dispatches" \
            -d '{"ref":"main"}'
          echo "Workflow rerun triggered due to previous step failure"
